language: python
python:
  - "3.6"
dist: bionic
cache: pip

git:
  depth: false

services:
  - docker

env:
  global:
    - CHROMEDRIVER_PATH=/usr/lib/chromium-browser/chromedriver
    - CHROMIUM_BROWSER=/usr/bin/chromium-browser

script:
  - docker build . || travis_terminate 1
  - sudo apt-get update || travis_terminate 1
  - sudo apt-get install -y chromium-chromedriver || travis_terminate 1
  - chromium-browser --version || travis_terminate 1
  - which chromium-browser || travis_terminate 1
  - ./test.sh || travis_terminate 1