name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Build:
    runs-on: ubuntu-20.04
    env:
      CHROMEDRIVER_PATH: /usr/lib/chromium-browser/chromedriver
      CHROMIUM_BROWSER: /usr/bin/chromium-browser
    steps:
      - name: "Set up Python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Cache Docker layers
        uses: actions/cache@v2
        continue-on-error: true # Because it's buggy sometimes
        with:
          path: /tmp/.buildx-cache
          key: frontend-${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            frontend-${{ runner.os }}-buildx-
      - uses: actions/checkout@v2
      - run: docker build .
      - run: apt-get update
      - run: apt-get install -y chromium-chromedriver
      - run: chromium-browser --version
      - run: which chromium-browser
      - run: ./test.sh
